import {
  ArrowDownUp,
  ArrowLeft,
  ArrowUpRight,
  AlertTriangle,
  ArrowRight,
  Bell,
  Calendar,
  CalendarDays,
  ChevronLeft,
  ChevronRight,
  ChevronDown,
  Command,
  CloudUpload,
  ClipboardCheck,
  CircleArrowLeft,
  Clock,
  CreditCard,
  CirclePlus,
  Dot,
  File,
  FileText,
  Filter,
  Frown,
  HelpCircle,
  Globe,
  Image,
  Laptop,
  Loader2,
  ListFilter,
  LayoutGrid,
  LayoutPanelLeft,
  Mail,
  Moon,
  MapPin,
  MessageSquareMore,
  MessageSquareDot,
  MessageCircle,
  MoreVertical,
  MoveUpRight,
  Pizza,
  Phone,
  Plus,
  Minus,
  Send,
  Settings,
  SunMedium,
  Trash,
  Timer,
  User,
  X,
  Menu,
  Leaf,
  Lock,
  LockOpen,
  Sparkles,
  Search,
  Eye,
  EyeOff,
  EllipsisVertical,
  Ellipsis,
  MoveRight,
  LogOut,
  Slash,
  BellDot,
  ShoppingCart,
  WalletMinimal,
  Watch,
  SquareActivity,
  UserMinus,
  Check,
  LucideProps,
  type Icon as LucideIcon,
} from "lucide-react";

export type Icon = typeof LucideIcon;

export type IconTypes = keyof typeof Icons;

export const Icons = {
  check: Check,
  arrowUpRight: ArrowUpRight,
  squareActivity: SquareActivity,
  clipboardCheck: ClipboardCheck,
  messageSquareMore: MessageSquareMore,
  shoppingCart: ShoppingCart,
  circleArrowLeft: CircleArrowLeft,
  bellDot: BellDot,
  phone: Phone,
  ellipsisV: Ellipsis,
  ellipsisVertical: EllipsisVertical,
  slash: Slash,
  sort: ArrowDownUp,
  arrowLeft: ArrowLeft,
  filter: ListFilter,
  filterFunnel: Filter,
  frown: Frown,
  search: Search,
  circlePlus: CirclePlus,
  dot: Dot,
  globe: Globe,
  mapPin: MapPin,
  calendar: Calendar,
  calendarDays: CalendarDays,
  clock: Clock,
  cloudUpload: CloudUpload,
  timer: Timer,
  logout: LogOut,
  moveRight: MoveRight,
  eye: Eye,
  eyeOff: EyeOff,
  sparkles: Sparkles,
  layoutGrid: LayoutGrid,
  bell: Bell,
  lock: Lock,
  lockOpen: LockOpen,
  layoutPanelLeft: LayoutPanelLeft,
  leaf: Leaf,
  logo: Command,
  close: X,
  minus: Minus,
  spinner: Loader2,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  chevronDown: ChevronDown,
  trash: Trash,
  post: FileText,
  page: File,
  media: Image,
  settings: Settings,
  billing: CreditCard,
  ellipsis: MoreVertical,
  add: Plus,
  warning: AlertTriangle,
  user: User,
  arrowRight: ArrowRight,
  help: HelpCircle,
  pizza: Pizza,
  sun: SunMedium,
  moon: Moon,
  laptop: Laptop,
  menu: Menu,
  walletMinimal: WalletMinimal,
  watch: Watch,
  messageSquareDot: MessageSquareDot,
  messageCircle: MessageCircle,
  moveUpRight: MoveUpRight,
  mail: Mail,
  send: Send,
  userMinus: UserMinus,
};
